# Human Tasks:
# 1. Verify network connectivity to all monitoring targets
# 2. Ensure firewall rules allow Prometheus to access target endpoints
# 3. Validate alertmanager endpoint is accessible
# 4. Confirm sufficient disk space for TSDB retention period

# Prometheus Configuration
# Version: 2.45.0

# Global configuration
# Requirement: Monitoring & Observability - Configure comprehensive metrics collection
global:
  scrape_interval: 15s     # How frequently to scrape targets
  evaluation_interval: 15s # How frequently to evaluate rules
  scrape_timeout: 10s     # How long until a scrape request times out

# Rule files to load
# Requirement: System Performance - Monitor API response times
# Requirement: Platform Stability - Track platform uptime
rule_files:
  - './rules/recording.yml'
  - './rules/alerts.yml'

# Scraping configurations
# Requirement: Monitoring & Observability - Configure comprehensive metrics collection
scrape_configs:
  # Edge Functions monitoring
  - job_name: 'edge-functions'
    metrics_path: '/metrics'
    scheme: 'https'
    static_configs:
      - targets: ['api.caseprep.vercel.app']
    relabel_configs:
      - source_labels: ['__address__']
        target_label: 'instance'

  # Supabase database monitoring
  - job_name: 'supabase'
    metrics_path: '/metrics'
    scheme: 'https'
    static_configs:
      - targets: ['db.caseprep.supabase.co:9090']

  # Redis monitoring
  - job_name: 'redis'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['redis:9121']

  # Docker containers monitoring
  - job_name: 'docker-containers'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:9090']

# Alerting configuration
# Requirement: Platform Stability - Track platform uptime
alerting:
  alert_relabel_configs:
    - source_labels: ['severity']
      target_label: 'alert_severity'
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

# Storage configuration
# Requirement: Monitoring & Observability - Configure comprehensive metrics collection
storage:
  tsdb:
    retention_time: '15d'    # How long to retain metrics
    retention_size: '50GB'   # Maximum storage size for metrics